### ISSUE TITLE
AttributeError: module 'flexiblecc' has no attribute 'BSpline'

### ISSUE THREAD

**Issue by hieubz** [SimonLBSoerensen/Flexible-Camera-Calibration#2]
when I used your lib to calibrate a camera, I found this bug:

Traceback (most recent call last):
  File "oldschoolcc_test.py", line 51, in <module>
    import flexiblecc as fcc
  File "/home/multi_cam_tracking/Flexible-Camera-Calibration-master/flexiblecc/__init__.py", line 1, in <module>
    from . import Metrics, BSpline, OldSchoolCC, BundleAdjustment
  File "/home/multi_cam_tracking/Flexible-Camera-Calibration-master/flexiblecc/BSpline/__init__.py", line 1, in <module>
    from .central_model import CentralModel
  File "/home/multi_cam_tracking/Flexible-Camera-Calibration-master/flexiblecc/BSpline/central_model.py", line 7, in <module>
    import flexiblecc.BSpline.knot_generators as kg
AttributeError: module 'flexiblecc' has no attribute 'BSpline'

**Comment by SimonLBSoerensen** [comment]
Thank you for spotting it 
I should have fixed the bug now in version 0.1.1
